name: Android Build

on:
  push:
    branches: [ "main", "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: cd OsmAnd-Cellular-Surround && chmod +x gradlew

    - name: Build with Gradle
      run: cd OsmAnd-Cellular-Surround && ./gradlew assembleRelease

    - name: Rename APK
      run: mv OsmAnd-Cellular-Surround/app/build/outputs/apk/release/app-release.apk OsmAnd-Cellular-Surround/app/build/outputs/apk/release/osmand-cellsurround.apk

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: osmand-cellsurround
        path: OsmAnd-Cellular-Surround/app/build/outputs/apk/release/osmand-cellsurround.apk
